export { split } from './split'
export type { Split, SplitOptions, SplitType, SplitA11y } from './split'
export { reveal } from './reveal'
export type { Reveal, RevealOptions, RevealFrom } from './reveal'
export { scramble } from './scramble'
export type { ScrambleOptions } from './scramble'
export { typewriter } from './typewriter'
export type { TypewriterOptions } from './typewriter'
export type { TextEffect } from './effect'
export { graphemes } from './segment'
